---
- name: Prepare local k3d cluster
  hosts: local
  gather_facts: false
  vars:
    cluster_name: parcheggia
  tasks:
    - name: Check k3d
      ansible.builtin.command: k3d version
      changed_when: false

    - name: Check Docker
      ansible.builtin.command: docker info
      changed_when: false

    - name: Check cluster
      ansible.builtin.command: k3d cluster list {{ cluster_name }}
      changed_when: false
      failed_when: false
      register: cluster_check

    - name: Create cluster
      ansible.builtin.command:
        argv:
          - k3d
          - cluster
          - create
          - "{{ cluster_name }}"
          - --servers
          - "1"
          - --agents
          - "0"
          - --wait
      when: cluster_check.rc != 0
